### PR TITLE
make passengers exit vehicle to a seat-linked exit attachment if it exists

### PR DESCRIPTION
**Pull request by milou2764**

### CODE REVIEW

**Comment by milou2764** [comment]
also the code has been refactored according to the known best practices

**Comment by milou2764** [comment]
here is an addon that implements the exit points : https://steamcommunity.com/sharedfiles/filedetails/?id=2696601197
just added the following
            ent.Exitpoints = {
                [1] = "exit_left",
                [2] = "exit_right",
                [3] = "exit_rear",
                [4] = "exit_rear",
                [5] = "exit_rear",
                [6] = "exit_rear"
            }
each string is an attachment name in the model

**Comment by Blu-x92** [comment]
i like the change, but i dont like all the change in formatting especially on the networkvars. Spreads it too far apart for me, seems a bit unnecessary

**Comment by milou2764** [comment]
ok i will redo the merge request with only the exit with attachment thing

**Pull request closed without merging**
